/**
 * The shared <html> skeleton every converter renders into. Provides:
 *  - dark-mode-aware modern CSS reset + system-fonts type
 *  - a sticky top bar with title + Cmd-F-style search box
 *  - a scroll-to-top button
 *  - mobile-responsive layout
 *
 * Converters fill in the body slot. Keep this opinionated and small:
 * one good design beats N themes.
 */
import { readFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import * as path from "node:path"

interface ShellOptions {
  title: string
  /** Optional kicker shown above the title (e.g. "WhatsApp · 2,341 messages") */
  eyebrow?: string
  /** The HTML body content — already escaped where needed. */
  body: string
  /** When true, mount the in-page search box (Cmd-F-like). Default true. */
  search?: boolean
  /** Footer note. Defaults to a quiet "Generated by html-anything · …". */
  footer?: string
  /** Extra CSS to inject after the base styles (converter-specific tweaks). */
  extraCss?: string
  /** Extra JS to inject before </body>. Use sparingly. */
  extraJs?: string
}

const __dirname = path.dirname(fileURLToPath(import.meta.url))
let baseCssCache: string | null = null
function loadBaseCss(): string {
  if (baseCssCache !== null) return baseCssCache
  const file = path.join(__dirname, "shell.css")
  try {
    baseCssCache = readFileSync(file, "utf8")
  } catch {
    baseCssCache = "" // CLI ran from src; ts files don't include .css siblings yet
  }
  return baseCssCache
}

export function htmlShell(opts: ShellOptions): string {
  const search = opts.search !== false
  const footer = opts.footer ?? `Generated by <a href="https://github.com/clockless-org/html-anything">html-anything</a> · open in any browser, share anywhere`
  const css = loadBaseCss()
  const extra = opts.extraCss ? `<style>${opts.extraCss}</style>` : ""
  const extraJs = opts.extraJs ? `<script>${opts.extraJs}</script>` : ""

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="color-scheme" content="light dark">
<title>${escapeHtml(opts.title)}</title>
<style>${css}</style>
${extra}
</head>
<body>
<header class="ha-bar">
  <div class="ha-bar__inner">
    <div class="ha-bar__brand">
      ${opts.eyebrow ? `<div class="ha-bar__eyebrow">${escapeHtml(opts.eyebrow)}</div>` : ""}
      <h1 class="ha-bar__title">${escapeHtml(opts.title)}</h1>
    </div>
    ${search ? `<input class="ha-bar__search" type="search" placeholder="Search…" aria-label="Search">` : ""}
  </div>
</header>
<main class="ha-main">
${opts.body}
</main>
<footer class="ha-footer">${footer}</footer>
<button class="ha-scrolltop" type="button" aria-label="Scroll to top">↑</button>
<script>${SHELL_JS}</script>
${extraJs}
</body>
</html>`
}

const SHELL_JS = `
(function () {
  // Search: hide elements with [data-searchable] that don't match.
  var input = document.querySelector('.ha-bar__search');
  if (input) {
    input.addEventListener('input', function () {
      var q = input.value.trim().toLowerCase();
      document.querySelectorAll('[data-searchable]').forEach(function (el) {
        var hay = el.getAttribute('data-searchable-text') || el.textContent || '';
        var hit = !q || hay.toLowerCase().indexOf(q) !== -1;
        el.classList.toggle('ha-hidden', !hit);
      });
    });
  }
  // Scroll-to-top
  var btn = document.querySelector('.ha-scrolltop');
  if (btn) {
    btn.addEventListener('click', function () {
      window.scrollTo({ top: 0, behavior: 'smooth' });
    });
    window.addEventListener('scroll', function () {
      btn.classList.toggle('ha-scrolltop--shown', window.scrollY > 500);
    });
  }
})();
`

export function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;")
}
